language: ruby
bundler_args: --without=acceptance
rvm:
  - 1.9.3
before_install:
  - gem install omnibus
script:
  - bundle install --binstubs
  - sudo mkdir -p /var/cache/omnibus
  - sudo chmod 777  /var/cache/omnibus
  - omnibus build project nginx-openresty 
